x = int(input())
y = int(input())
addition = (x+y)
subtract = (x-y)
multiplication = (x*y)
division = (x//y)
power2_x = (x*x)
power2_y = (y*y)
print(x, y, addition, subtract, multiplication, division, power2_x, power2_y)
