x = int(input())
y = int(input())
addition = (x+y)
subtract = (x-y)
multiplication = (x*y)
division = (x//y)
power2_x = (x*x)
power2_y = (y*y)
print("Hola, por favor ingrese valores")
print("x:" x, "y:" y)
print(addition, subtract, multiplication, division, power2_x, power2_y)
